version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_SYNC: ${DATABASE_URL_SYNC}
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A celery_worker.app worker -B --loglevel=info
    volumes:
      - .:/app
    environment:
      ENVIRONMENT: development
    depends_on:
      - web
      - redis

volumes:
  db_data:
  redis_data:
